### ISSUE TITLE
Cannot create / post item

### ISSUE THREAD

**Issue by Nothinel** [elabftw/elabapi-python#1]
Hello,

thanks for the great work so far. 
When I try to create an item, I get an Error with the body:
HTTP response body: b'{"code":403,"message":"Access Forbidden","description":"The id parameter is not valid!"}'
I suspect this might indicate that I am not allowed to create items, but I would not understand why that is.
I am able to post / create experiments
I am the Sysadmin of a fresh install of elabFTW 4.4.2
My API-key has read/write permissions and was created via my "User Panel"
I am using the current version of elabapi_python (installed via pip)

My code to test (mostly copied from the examples)

```python
#!/usr/bin/env python
import time
import datetime
import elabapi_python
from elabapi_python.rest import ApiException

#########################
#         CONFIG        #
#########################
API_HOST_URL = 'https://172.26.28.186:443/api/v2'
# replace with your api key
API_KEY = 'api_key_copied_from_user_panel'
# number of days to look back
PERIOD_IN_DAYS = 20
#########################
#      END CONFIG       #
#########################

# Configure the api client
configuration = elabapi_python.Configuration()
configuration.api_key['api_key'] = API_KEY
configuration.api_key_prefix['api_key'] = 'Authorization'
configuration.host = API_HOST_URL
configuration.debug = False
configuration.verify_ssl = False

# create an instance of the API class
api_client = elabapi_python.ApiClient(configuration)
# fix issue with Authorization header not being properly set by the generated lib
api_client.set_default_header(header_name='Authorization', header_value=API_KEY)

# create an instance of the apis
itemsApi = elabapi_python.ItemsApi(api_client)
itemstypesApi = elabapi_python.ItemsTypesApi(api_client)
experimentsApi = elabapi_python.ExperimentsApi(api_client)
uploadsApi = elabapi_python.UploadsApi(api_client)

experimentsApi.post_experiment()
itemsApi.post_item()
```

Kind regards,

Konrad

**Comment by NicolasCARPi** [comment]
Hello,

First, when posting code, add the language after the first `~~~` (or backticks as you did) so there is syntax highlighting ;)

Second, you'll find a working code here:

https://github.com/elabftw/elabapi-python/blob/3fb18130fb65d88f3ed15100a96a10e2de305c45/examples/05.py#L30-L40

Best,
~Nico
