### ISSUE TITLE
TypeError for experiment templates

### ISSUE THREAD

**Issue by QB-SZ** [elabftw/elabapi-python#15]
I am trying to post a new experiment and patch it with a template I download from elab. I am guessing that is the intended way of creating an experiment from template via the API?

The problem is the type of the downloaded template which is "ExperimentTemplate" as set in the get_experiment_template_with_http_info(method) in return the response_type='ExperimentTemplate'. In reality it is a json object but I think because of that line it is not detected as such, so when I try to for example to print it with json.dumps() I get a "TypeError: the JSON object must be str, bytes or bytearray, not ExperimentTemplate"

**Comment by NicolasCARPi** [comment]
> I am guessing that is the intended way of creating an experiment from template via the API?

No, you can pass the template ID directly to the POST to experiments with the `category_id`. I realize now it should be renamed `template_id`.

When you use the python lib, you can access attributes like so: ExperimentTemplate.id or .title, etc... If you don't want the lib to interpret the response and create a python object, use `_preload_content=False` in your read call ([example](https://github.com/elabftw/elabapi-python/blob/49673f5057a0fa841d4d038de248e1e0da900bb9/examples/01.py#L49)).

**Comment by QB-SZ** [comment]
Hah, thanks! I was almost certain it has to be that way. renaming it would definitely make it more intuitive.
