### ISSUE TITLE
patch_experiment_template() unable to change pin/unpinned templates via API

### ISSUE THREAD

**Issue by Robert-Wagner-INP** [elabftw/elabapi-python#18]
Hello,
I am using ElabFTW v. 5.0.3 and have a problem regarding the change of the pinned/unpinned status of my templates.
I can properly pull my templates via their ID but the body of the api response is

 'is_pinned': None,

Regardless of whether the template was manually pinned or unpinned in ElabFTW. 
The following patch approach:
api_instance.patch_experiment_template(177, body={"is_pinned":1})

results in:
HTTP response body: b'{"code":400,"message":"Bad Request","description":"Invalid update target."}'

I would appreciate any advice on how to solve my problem.

**Comment by NicolasCARPi** [comment]
What's your elabapi-python version?

**Comment by Robert-Wagner-INP** [comment]
Sorry for missing information:
pip said
Name: elabapi-python
Version: 5.0.2

**Comment by mhxion** [comment]
`pin` is an action. See the [spec](https://github.com/elabftw/elabftw/blob/hypernext/apidoc/v2/openapi.yaml#L1912). So you have to pass the body like the following:
```py
body={"action": "pin", "pinned": 1}
```
Note: It worked with `curl`-equivalent (😉) for me. I haven't tested your entire Python code, or I have no idea if there's some other issue with your eLab instance. If it works, you can also thank @alexander-haller.

**Comment by NicolasCARPi** [comment]
Yes, thanks @mhxion , that's exactly that. BTW, the action is toggle, so the "pinned" parameter does nothing.

**Comment by mhxion** [comment]
> so the "pinned" parameter does nothing.

I just realized that, and already updated my code. Thanks for pointing it out.

**Comment by Robert-Wagner-INP** [comment]
Thank you very much, the problem is solved.
