### ISSUE TITLE
Adding custom timestamps to steps

### ISSUE THREAD

**Issue by wolferave** [elabftw/elabapi-python#20]
Hello,

maybe I didn't fully understand the purpose of steps but I have a problem modifying them via the API. Sadly, as far as I understand it is only possible to mark them as finished and the timestamp is set to the time the API request arrived. Is there a way to set the timestamp manually to a custom time (e.g. for using a log file of a device to check if and when the user completed all necessary steps)? This would be really nice to allow users to check after an experiment if and when they finished which step without clicking on the checkboxes every time.

Thanks you in advance.

**Comment by NicolasCARPi** [comment]
Hello,

Indeed, the `finished_time` column is hardcoded as `TIME()` during the "toggle finish" action. But is available as param in the PATCH, so you can PATCH it to whatever you want.

**Comment by wolferave** [comment]
Sorry my bad! I tried to mark the step as finished and modify its `finished_time` in the same PATCH. If I do it afterwards it works just fine. 
Thanks a lot for the quick help!!!
