### ISSUE TITLE
Weird output of item attributes

### ISSUE THREAD

**Issue by QB-SZ** [elabftw/elabapi-python#21]
I have elabftw v5.0.0 installed and recently ran into this:

#  I load an item the usual way:
item = ItemApi_instance.get_item(id=123)
# Then print the item objects attributes
print(item.__dict__)
# Which gives this (minus some values I have replaced by ... for confidentiality)

~~~python
{
'_is_bookable': 0, 
'_canbook': '{"base": 40, "teams": [], "users": [], "teamgroups": []}',
'_book_max_minutes': 0,
'_book_max_slots': 0,
'_book_can_overlap': 1,
'_book_users_can_in_past': None,
'_book_is_cancellable': 1,
'_book_cancel_minutes': 0,
**'discriminator': None,**
'_access_key': None,
'_body': '',
'_body_html': '',
'_canread': '{"base": 40, "teams": [], "users": [], "teamgroups": []}',
'_canwrite': '{"base": 30, "teams": [], "users": [], "teamgroups": []}',
'_category': 21,
'_category_color': '22c32d',
'_category_title': 'Sample_v2',
'_comments': [],
'_content_type': 1,
'_created_at': '2024-06-27 16:16:25',
'_custom_id': None,
**'_Entity__date'**: '2024-06-27',
'_elabid': '...',
'_experiments_links': [],
'_firstname': '...',
'_fullname': '...',
'_has_attachement': None,
'_has_comment': 0,
'_id': 1716,
'_items_links': [],
'_lastchangeby': 1,
'_lastname': '...',
'_locked': 0,
**'_lockedby'**: None,
**'_locked_at'**: None,
'_metadata': [...],
'_modified_at': '2024-07-15 14:33:45',
'_next_step': None,
'_orcid': None,
'_page': 'database',
'_rating': 0,
'_recent_comment': None,
'_related_experiments_links': [],
'_related_items_links': [],
'_sharelink': '...',
'_state': 1,
'_status': 4,
'_status_color':'29aeb9',
'_status_title': 'In use',
'_steps': [],
'_tags': None,
'_tags_id': None,
'_team': 1,
'_timestamped': 0,
'_timestampedby': None,
'_timestamped_at': None,
'_title': 'Red Ice',
'_type': 'items',
'_up_item_id': None,
'_uploads': [],
'_userid': 34
}

~~~

My questions are the following:
Why does every attribute have a leading underscore?
What is discriminator and why does it not have a leading underscore?
What is going on with '_Entity__date'? Entity should have a lower case to begin with but also I feel entity and date should be two separate attributes. 

I have highlighted two more inconsistencies in naming convention as a minor improvement.
Here is how the head of the items info looks like on the API online, note no leading underscores:
![image](https://github.com/user-attachments/assets/505e0475-277e-42f1-80d7-aac7ab41830c)

**Comment by QB-SZ** [comment]
Sorry, I realized  I should not go the way via __dict__ and just use item.items() to access the dict keys ...

**Comment by NicolasCARPi** [comment]
Hello,

1. What is the `.dict` attribute? In any case, you can simply do `print(item)`, it works fine. And you won't see underscores.
2. Indeed the `date` property is prefixed with an underscore, and I believe that's the swagger-codegen adding it to prevent a clash with internal name or something. You will find many similar issues if you google `swagger codegen underscore`. I don't have a solution to this behavior. It is not a discrepency in eLab's spec, but rather an edge case of the python library generating code. I'm surprised it wasn't spotted before.
3. Latest version is 5.0.4, you must always update to the latest stable version, you are missing 4 important patches.
4. In this case it's not an issue, but when reporting a bug like this, mention your python version and elabapi-python version. In a bug report, there is never _too much_ information ;)

**Comment by QB-SZ** [comment]
Hi, thanks!
Indeed, it is much simpler to just print(item). I asked for the update of our elab instance to be updated, sysadmins are not on top of the updates it seems ;)

**Comment by mhxion** [comment]
> Then print the item objects attributes
>
> print(item.dict)

I cannot reproduce the output with `dict`, actually `dict` isn't an attribute for `elabapi_python.Item`. But I think you mean `__dict__`. Pretty much all Python objects has `__dict__` (see below). Swagger seems to add the the response key as attributes to the calling API likely by taking advantage of `__getattribute__`. So you are able do this, `item.available` and it will work. I am not a big fan of this, as it takes gives you the impression that `Item` class has a true understanding of the eLabFTW OpenAPI spec. 

> What is the .dict attribute? 

Maybe you already know what [`__dict__`](https://docs.python.org/3/library/stdtypes.html#object.__dict__) is.
