### ISSUE TITLE
Adding package documentation

### ISSUE THREAD

**Issue by jat255** [elabftw/elabapi-python#5]
Hi Nico,

I was leading a student through getting started with this library, and as far as I could find, there's no documentation anywhere online about the generated code, so it took a little bit to work out the various methods available (i.e. that `/experiments` corresponds to `ExperimentApi.read_experiments()`, etc.). It's not so hard once you work through it once (especially if you know Python) but I think having the python docs posted somewhere would be helpful when getting started and for more inexperienced programmers.

I was playing with building the library locally and noticed that it generates docs along with the library together with a `README.md` and `docs/` folder that could be either hosted somewhere, or even just in this repo (and then Github can render the markdown files).

I made an example on this branch where I committed the `/docs` folder and added the links to the top-level README: https://github.com/jat255/elabapi-python/tree/doc_test

If nothing else, I would suggest that this table (https://github.com/jat255/elabapi-python/tree/doc_test#documentation-for-api-endpoints) be put somewhere and linked from the API documentation page in the main ELabFTW documentation. 

What do you think?

**Comment by NicolasCARPi** [comment]
I'll look into the best option.

I wonder why this page: https://pypi.org/project/elabapi-python/ doesn't show the full README!

**Comment by NicolasCARPi** [comment]
Now the html doc is also generated and hosted: https://doc.elabftw.net/api/elabapi-html/

But I strongly believe documentation by examples, the ones in the examples folder of this repository is better than this generated one. Still, it's good to have a reference for the available methods. As a bonus, you get code examples for many languages!

**Comment by NicolasCARPi** [comment]
Fun fact, it seems this generated html doc with swagger-codegen uses [apidoc](https://github.com/apidoc/apidoc), a software I maintain. But it's an old version.

**Comment by NicolasCARPi** [comment]
The library name is normally correctly configured, it might be that because this html2 thing hasn't been touched in years, it is not picked up properly. I'd appreciate if you can try and find the time to look into it. If you find a parameter to add to [this line](https://github.com/elabftw/elabapi-python/blob/b53fb011563b8cb5973c65b06e533ecde706b8e0/helper.sh#L29), please let me know.

**Comment by jat255** [comment]
Turns out it's a pretty simple fix. Just a one line change to the `config.json` file changed in the linked PR

**Comment by NicolasCARPi** [comment]
doc has been updated on doc.elabftw.net!
